[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"

[rpc_endpoints]
blast = "https://rpc.envelop.is/blast"

[fmt]
int_types = "long"
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"
single_line_statement_blocks = "single"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
